/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_abilix_control_process_ProcessControl */

#ifndef _Included_com_abilix_control_process_ProcessControl
#define _Included_com_abilix_control_process_ProcessControl
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_abilix_control_process_ProcessControl_timerslack
  (JNIEnv *env, jobject thiz,jint tid,jint period)

#ifdef __cplusplus
}
#endif
#endif


